essay-images: /essays/images

directory-sheet: 'https://docs.google.com/spreadsheets/d/1pP8KhM3E5rmA3ce2Q3oKNFmqJHnEuLT15Nkp_NI61u8/edit?usp=sharing#gid=0'

defaults:
  -
    scope:
      path: "essays"
    values:
      layout: "base"
